# Generated by Django 4.0 on 2023-06-01 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Trader',
        ),
    ]
